import jsPDF from "jspdf";
import JSZip from "jszip";
import { saveAs } from "file-saver";

interface ExportQuestion {
  questionNumber: number;
  text: string;
  marks: number;
  unit: string;
  difficulty: string;
}

interface PaperMeta {
  collegeName?: string;
  subjectName: string;
  subjectCode?: string;
  examType?: string;
  duration?: string;
  maxMarks: number;
  setLabel?: string;
  watermark?: boolean;
  paperId?: string;
}

function buildTextContent(questions: ExportQuestion[], meta: PaperMeta): string {
  const lines: string[] = [];
  if (meta.collegeName) lines.push(meta.collegeName.toUpperCase());
  if (meta.examType) lines.push(`${meta.examType} Examination`);
  lines.push(`Subject: ${meta.subjectName}${meta.subjectCode ? ` (${meta.subjectCode})` : ""}`);
  if (meta.duration) lines.push(`Duration: ${meta.duration}`);
  lines.push(`Max Marks: ${meta.maxMarks}`);
  if (meta.setLabel) lines.push(`Set: ${meta.setLabel}`);
  lines.push("", "Instructions:", "1. Answer all questions.", "2. Write neat and legible answers.", "");

  const sectionA = questions.filter(q => q.marks === 2);
  const sectionB = questions.filter(q => q.marks === 5);
  const sectionC = questions.filter(q => q.marks === 10);

  const addSection = (title: string, qs: ExportQuestion[], markLabel: string) => {
    if (qs.length === 0) return;
    lines.push(`--- ${title} (${markLabel}) ---`);
    qs.forEach(q => lines.push(`${q.questionNumber}. ${q.text} [${q.marks}M]`));
    lines.push("");
  };

  addSection("Section A", sectionA, "2 Marks Each");
  addSection("Section B", sectionB, "5 Marks Each");
  addSection("Section C", sectionC, "10 Marks Each");

  if (meta.watermark) lines.push("", "Generated by CognitoQ");
  if (meta.paperId) lines.push(`Paper ID: ${meta.paperId}`);
  return lines.join("\n");
}

export function exportAsTxt(questions: ExportQuestion[], meta: PaperMeta) {
  const content = buildTextContent(questions, meta);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  saveAs(blob, `${meta.subjectName.replace(/\s+/g, "_")}_${meta.setLabel || "Paper"}.txt`);
}

export function exportAsPdf(questions: ExportQuestion[], meta: PaperMeta) {
  const doc = new jsPDF();
  let y = 15;
  const margin = 15;
  const pageWidth = doc.internal.pageSize.getWidth();

  const addLine = (text: string, fontSize = 10, bold = false) => {
    if (y > 275) { doc.addPage(); y = 15; }
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.5) + 2;
  };

  if (meta.collegeName) { addLine(meta.collegeName.toUpperCase(), 14, true); }
  if (meta.examType) addLine(`${meta.examType} Examination`, 11, false);
  addLine(`Subject: ${meta.subjectName}${meta.subjectCode ? ` (${meta.subjectCode})` : ""}`, 11, true);
  const infoLine = [meta.duration ? `Duration: ${meta.duration}` : "", `Max Marks: ${meta.maxMarks}`].filter(Boolean).join("  |  ");
  addLine(infoLine, 10);
  if (meta.setLabel) addLine(`Set: ${meta.setLabel}`, 10, true);
  y += 3;
  doc.setDrawColor(0); doc.line(margin, y, pageWidth - margin, y); y += 5;

  addLine("Instructions:", 9, true);
  addLine("1. Answer all questions.  2. Write neat and legible answers.", 9);
  y += 4;

  const sectionA = questions.filter(q => q.marks === 2);
  const sectionB = questions.filter(q => q.marks === 5);
  const sectionC = questions.filter(q => q.marks === 10);

  const addSection = (title: string, qs: ExportQuestion[], markLabel: string) => {
    if (qs.length === 0) return;
    addLine(`${title} — ${markLabel}`, 11, true);
    y += 1;
    qs.forEach(q => addLine(`${q.questionNumber}. ${q.text}  [${q.marks}M]`, 10));
    y += 3;
  };

  addSection("Section A", sectionA, "2 Marks Each");
  addSection("Section B", sectionB, "5 Marks Each");
  addSection("Section C", sectionC, "10 Marks Each");

  // Footer
  if (meta.watermark) {
    doc.setFontSize(8); doc.setTextColor(180);
    doc.text("Generated by CognitoQ", margin, 290);
  }
  if (meta.paperId) {
    doc.setFontSize(7); doc.setTextColor(150);
    doc.text(`Paper ID: ${meta.paperId}`, pageWidth - margin - 40, 290);
  }

  doc.save(`${meta.subjectName.replace(/\s+/g, "_")}_${meta.setLabel || "Paper"}.pdf`);
}

export function exportAsDocx(questions: ExportQuestion[], meta: PaperMeta) {
  // Generate a rich-text HTML that can be opened in Word
  let html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><style>body{font-family:Calibri,sans-serif;font-size:11pt;margin:1in}h1{font-size:16pt;text-align:center}h2{font-size:13pt}h3{font-size:12pt;margin-top:18pt}.info{text-align:center;font-size:10pt;color:#555}table{width:100%;border-collapse:collapse}td{padding:4pt}</style></head><body>`;
  
  if (meta.collegeName) html += `<h1>${meta.collegeName.toUpperCase()}</h1>`;
  if (meta.examType) html += `<p class="info">${meta.examType} Examination</p>`;
  html += `<h2 style="text-align:center">${meta.subjectName}${meta.subjectCode ? ` (${meta.subjectCode})` : ""}</h2>`;
  html += `<p class="info">${[meta.duration ? `Duration: ${meta.duration}` : "", `Max Marks: ${meta.maxMarks}`, meta.setLabel ? `Set: ${meta.setLabel}` : ""].filter(Boolean).join(" | ")}</p>`;
  html += `<hr/><p><b>Instructions:</b> Answer all questions. Write neat and legible answers.</p>`;

  const sectionA = questions.filter(q => q.marks === 2);
  const sectionB = questions.filter(q => q.marks === 5);
  const sectionC = questions.filter(q => q.marks === 10);

  const addSection = (title: string, qs: ExportQuestion[], markLabel: string) => {
    if (qs.length === 0) return;
    html += `<h3>${title} — ${markLabel}</h3><table>`;
    qs.forEach(q => { html += `<tr><td style="width:30pt;vertical-align:top">${q.questionNumber}.</td><td>${q.text}</td><td style="width:30pt;text-align:right">[${q.marks}M]</td></tr>`; });
    html += `</table>`;
  };
  addSection("Section A", sectionA, "2 Marks Each");
  addSection("Section B", sectionB, "5 Marks Each");
  addSection("Section C", sectionC, "10 Marks Each");

  if (meta.watermark) html += `<p style="margin-top:40pt;font-size:8pt;color:#aaa">Generated by CognitoQ</p>`;
  html += `</body></html>`;

  const blob = new Blob([html], { type: "application/msword" });
  saveAs(blob, `${meta.subjectName.replace(/\s+/g, "_")}_${meta.setLabel || "Paper"}.doc`);
}

export async function exportAsZip(
  variants: ExportQuestion[][],
  meta: PaperMeta,
  format: "pdf" | "txt" = "txt"
) {
  const zip = new JSZip();
  const labels = ["A", "B", "C", "D", "E"];

  variants.forEach((questions, i) => {
    const label = labels[i] || String(i + 1);
    const variantMeta = { ...meta, setLabel: `Set ${label}` };
    const content = buildTextContent(questions, variantMeta);
    zip.file(`Set_${label}.txt`, content);
  });

  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${meta.subjectName.replace(/\s+/g, "_")}_AllSets.zip`);
}
