import jsPDF from "jspdf";
import JSZip from "jszip";
import { saveAs } from "file-saver";

interface ExportQuestion {
  questionNumber: number;
  text: string;
  marks: number;
  unit: string;
  difficulty: string;
  orAlternativeText?: string;
}

interface SectionConfig {
  id: string;
  name: string;
  marks: number;
  totalQuestions: number;
  questionsToAnswer: number;
  enableOr: boolean;
}

interface PaperMeta {
  collegeName?: string;
  subjectName: string;
  subjectCode?: string;
  examType?: string;
  duration?: string;
  maxMarks: number;
  setLabel?: string;
  watermark?: boolean;
  paperId?: string;
  sections?: SectionConfig[];
}

function groupBySection(questions: ExportQuestion[], meta: PaperMeta): { title: string; instruction: string; markLabel: string; questions: ExportQuestion[] }[] {
  if (meta.sections && meta.sections.length > 0) {
    let offset = 0;
    return meta.sections.map(section => {
      const sectionQs = questions.slice(offset, offset + section.totalQuestions);
      offset += section.totalQuestions;
      const instruction = section.questionsToAnswer < section.totalQuestions
        ? `Answer any ${section.questionsToAnswer} out of ${section.totalQuestions} questions`
        : "Answer all questions";
      return {
        title: section.name,
        instruction,
        markLabel: `${section.marks} Marks Each`,
        questions: sectionQs,
      };
    }).filter(s => s.questions.length > 0);
  }

  // Fallback: group by marks
  const sectionA = questions.filter(q => q.marks === 2);
  const sectionB = questions.filter(q => q.marks === 5);
  const sectionC = questions.filter(q => q.marks === 10);
  const result: { title: string; instruction: string; markLabel: string; questions: ExportQuestion[] }[] = [];
  if (sectionA.length > 0) result.push({ title: "PART – A", instruction: "Answer all questions", markLabel: "2 Marks Each", questions: sectionA });
  if (sectionB.length > 0) result.push({ title: "PART – B", instruction: "Answer all questions", markLabel: "5 Marks Each", questions: sectionB });
  if (sectionC.length > 0) result.push({ title: "PART – C", instruction: "Answer all questions", markLabel: "10 Marks Each", questions: sectionC });
  return result;
}

function buildTextContent(questions: ExportQuestion[], meta: PaperMeta): string {
  const lines: string[] = [];
  if (meta.collegeName) lines.push(meta.collegeName.toUpperCase());
  if (meta.examType) lines.push(`${meta.examType} Examination`);
  lines.push(`Subject: ${meta.subjectName}${meta.subjectCode ? ` (${meta.subjectCode})` : ""}`);
  if (meta.duration) lines.push(`Duration: ${meta.duration}`);
  lines.push(`Max Marks: ${meta.maxMarks}`);
  if (meta.setLabel) lines.push(`Set: ${meta.setLabel}`);
  lines.push("");

  const sectionGroups = groupBySection(questions, meta);
  sectionGroups.forEach(section => {
    lines.push(`═══ ${section.title} (${section.markLabel}) ═══`);
    lines.push(`[${section.instruction}]`);
    lines.push("");
    section.questions.forEach(q => {
      if (q.orAlternativeText) {
        lines.push(`${q.questionNumber}. A) ${q.text} [${q.marks}M]`);
        lines.push(`              OR`);
        lines.push(`${q.questionNumber}. B) ${q.orAlternativeText} [${q.marks}M]`);
      } else {
        lines.push(`${q.questionNumber}. ${q.text} [${q.marks}M]`);
      }
    });
    lines.push("");
  });
  lines.push("");
  lines.push("✓ AI Validated Paper");
  if (meta.watermark) lines.push("Generated by CognitoQ");
  if (meta.paperId) lines.push(`Paper ID: ${meta.paperId}`);
  return lines.join("\n");
}

export function exportAsTxt(questions: ExportQuestion[], meta: PaperMeta) {
  const content = buildTextContent(questions, meta);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  saveAs(blob, `${meta.subjectName.replace(/\s+/g, "_")}_${meta.setLabel || "Paper"}.txt`);
}

export function exportAsPdf(questions: ExportQuestion[], meta: PaperMeta) {
  const doc = new jsPDF();
  let y = 15;
  const margin = 15;
  const pageWidth = doc.internal.pageSize.getWidth();

  const addLine = (text: string, fontSize = 10, bold = false) => {
    if (y > 275) { doc.addPage(); y = 15; }
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(0);
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.5) + 2;
  };

  const addCenteredLine = (text: string, fontSize = 10, bold = false) => {
    if (y > 275) { doc.addPage(); y = 15; }
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(0);
    doc.text(text, pageWidth / 2, y, { align: "center" });
    y += fontSize * 0.5 + 2;
  };

  if (meta.collegeName) { addCenteredLine(meta.collegeName.toUpperCase(), 14, true); }
  if (meta.examType) addCenteredLine(`${meta.examType} Examination`, 11, false);
  addCenteredLine(`${meta.subjectName}${meta.subjectCode ? ` (${meta.subjectCode})` : ""}`, 12, true);
  const infoLine = [meta.duration ? `Duration: ${meta.duration}` : "", `Max Marks: ${meta.maxMarks}`].filter(Boolean).join("  |  ");
  addCenteredLine(infoLine, 10);
  if (meta.setLabel) addCenteredLine(`${meta.setLabel}`, 10, true);
  y += 3;
  doc.setDrawColor(0); doc.line(margin, y, pageWidth - margin, y); y += 5;

  const sectionGroups = groupBySection(questions, meta);
  sectionGroups.forEach((section, sIdx) => {
    if (sIdx > 0) { y += 4; doc.setDrawColor(200); doc.line(margin, y, pageWidth - margin, y); y += 4; }
    addLine(`${section.title} — ${section.markLabel}`, 11, true);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100);
    doc.text(section.instruction, margin, y);
    doc.setTextColor(0);
    y += 6;

    section.questions.forEach(q => {
      if (q.orAlternativeText) {
        addLine(`${q.questionNumber}. A) ${q.text}  [${q.marks}M]`, 10);
        // OR divider
        if (y > 275) { doc.addPage(); y = 15; }
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(100);
        doc.text("OR", margin + 20, y);
        doc.setTextColor(0);
        y += 5;
        addLine(`${q.questionNumber}. B) ${q.orAlternativeText}  [${q.marks}M]`, 10);
        y += 2;
      } else {
        addLine(`${q.questionNumber}. ${q.text}  [${q.marks}M]`, 10);
      }
    });
    y += 3;
  });

  // AI Validated badge
  doc.setFontSize(9); doc.setFont("helvetica", "bold"); doc.setTextColor(34, 139, 34);
  doc.text("✓ AI Validated Paper", pageWidth / 2, 284, { align: "center" });

  // Footer
  if (meta.watermark) {
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(180);
    doc.text("Generated by CognitoQ", margin, 290);
  }
  if (meta.paperId) {
    doc.setFontSize(7); doc.setTextColor(150);
    doc.text(`Paper ID: ${meta.paperId}`, pageWidth - margin - 40, 290);
  }

  doc.save(`${meta.subjectName.replace(/\s+/g, "_")}_${meta.setLabel || "Paper"}.pdf`);
}

export function exportAsDocx(questions: ExportQuestion[], meta: PaperMeta) {
  let html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><style>body{font-family:Calibri,sans-serif;font-size:11pt;margin:1in}h1{font-size:16pt;text-align:center}h2{font-size:13pt}h3{font-size:12pt;margin-top:18pt}.info{text-align:center;font-size:10pt;color:#555}.instruction{font-style:italic;color:#666;font-size:9pt;margin-bottom:8pt}.or-divider{text-align:center;font-weight:bold;color:#888;margin:4pt 0}table{width:100%;border-collapse:collapse}td{padding:4pt}</style></head><body>`;
  
  if (meta.collegeName) html += `<h1>${meta.collegeName.toUpperCase()}</h1>`;
  if (meta.examType) html += `<p class="info">${meta.examType} Examination</p>`;
  html += `<h2 style="text-align:center">${meta.subjectName}${meta.subjectCode ? ` (${meta.subjectCode})` : ""}</h2>`;
  html += `<p class="info">${[meta.duration ? `Duration: ${meta.duration}` : "", `Max Marks: ${meta.maxMarks}`, meta.setLabel ? `${meta.setLabel}` : ""].filter(Boolean).join(" | ")}</p>`;
  html += `<hr/>`;

  const sectionGroups = groupBySection(questions, meta);
  sectionGroups.forEach(section => {
    html += `<h3>${section.title} — ${section.markLabel}</h3>`;
    html += `<p class="instruction">${section.instruction}</p>`;
    html += `<table>`;
    section.questions.forEach(q => {
      if (q.orAlternativeText) {
        html += `<tr><td style="width:30pt;vertical-align:top">${q.questionNumber}.</td><td><b>A)</b> ${q.text}</td><td style="width:30pt;text-align:right">[${q.marks}M]</td></tr>`;
        html += `<tr><td></td><td class="or-divider">OR</td><td></td></tr>`;
        html += `<tr><td style="width:30pt;vertical-align:top">${q.questionNumber}.</td><td><b>B)</b> ${q.orAlternativeText}</td><td style="width:30pt;text-align:right">[${q.marks}M]</td></tr>`;
      } else {
        html += `<tr><td style="width:30pt;vertical-align:top">${q.questionNumber}.</td><td>${q.text}</td><td style="width:30pt;text-align:right">[${q.marks}M]</td></tr>`;
      }
    });
    html += `</table>`;
  });

  if (meta.watermark) html += `<p style="margin-top:40pt;font-size:8pt;color:#aaa">Generated by CognitoQ</p>`;
  html += `</body></html>`;

  const blob = new Blob([html], { type: "application/msword" });
  saveAs(blob, `${meta.subjectName.replace(/\s+/g, "_")}_${meta.setLabel || "Paper"}.doc`);
}

export async function exportAsZip(
  variants: ExportQuestion[][],
  meta: PaperMeta,
  format: "pdf" | "txt" = "txt"
) {
  const zip = new JSZip();
  const labels = ["A", "B", "C", "D", "E"];

  variants.forEach((questions, i) => {
    const label = labels[i] || String(i + 1);
    const variantMeta = { ...meta, setLabel: `Set ${label}` };
    const content = buildTextContent(questions, variantMeta);
    zip.file(`Set_${label}.txt`, content);
  });

  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${meta.subjectName.replace(/\s+/g, "_")}_AllSets.zip`);
}
