import { useState, useEffect } from "react";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { motion } from "framer-motion";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import {
  Settings, FileText, Brain, BookOpen, Palette, Shield, Download,
  RotateCcw, Save, Lock, AlertTriangle
} from "lucide-react";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
  AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger
} from "@/components/ui/alert-dialog";

const STORAGE_KEY = "cognitoq-settings";

interface AppSettings {
  // General
  collegeName: string;
  defaultExamType: string;
  defaultDuration: string;
  defaultMaxMarks: string;
  // Paper
  defaultSections: string;
  defaultMarksPattern: string;
  defaultDifficulty: string;
  orQuestionsDefault: boolean;
  // AI
  aiMode: string;
  shuffleLimit: string;
  // Branding
  logoUrl: string;
  headerFormat: string;
  paperTheme: string;
  // Security
  sessionTimeout: string;
  approvalNotifications: boolean;
  activityLogs: boolean;
  // Export
  defaultExportFormat: string;
  watermarkEnabled: boolean;
  watermarkText: string;
  footerText: string;
  // Paper defaults
  includeInstructions: boolean;
  autoNumberQuestions: boolean;
  showMarksAlignment: boolean;
}

const defaultSettings: AppSettings = {
  collegeName: "",
  defaultExamType: "end",
  defaultDuration: "180",
  defaultMaxMarks: "100",
  defaultSections: "3",
  defaultMarksPattern: "2-5-10",
  defaultDifficulty: "mixed",
  orQuestionsDefault: true,
  aiMode: "balanced",
  shuffleLimit: "4",
  logoUrl: "",
  headerFormat: "centered",
  paperTheme: "classic",
  sessionTimeout: "30",
  approvalNotifications: true,
  activityLogs: true,
  defaultExportFormat: "pdf",
  watermarkEnabled: false,
  watermarkText: "Generated by CognitoQ",
  footerText: "CognitoQ – AI Validated Paper",
  includeInstructions: true,
  autoNumberQuestions: true,
  showMarksAlignment: true,
};

function loadSettings(): AppSettings {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return { ...defaultSettings, ...JSON.parse(raw) };
  } catch {}
  return { ...defaultSettings };
}

const SectionCard = ({ children, title, icon: Icon, delay = 0 }: { children: React.ReactNode; title: string; icon: React.ElementType; delay?: number }) => (
  <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay }} className="rounded-xl border border-border bg-card p-5 space-y-4">
    <div className="flex items-center gap-2">
      <Icon className="h-4 w-4 text-accent" />
      <h3 className="font-semibold text-foreground">{title}</h3>
    </div>
    <Separator />
    {children}
  </motion.div>
);

const AdminBadge = () => (
  <Badge variant="outline" className="text-[10px] gap-1 border-destructive/40 text-destructive">
    <Lock className="h-3 w-3" /> Admin Only
  </Badge>
);

export default function SettingsPage() {
  const { role } = useAuth();
  const isAdmin = role === "admin";
  const [settings, setSettings] = useState<AppSettings>(loadSettings);
  const [hasChanges, setHasChanges] = useState(false);

  const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => {
    setSettings(prev => ({ ...prev, [key]: value }));
    setHasChanges(true);
  };

  const save = () => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
    setHasChanges(false);
    toast.success("Settings saved successfully!");
  };

  const resetAll = () => {
    setSettings({ ...defaultSettings });
    localStorage.removeItem(STORAGE_KEY);
    setHasChanges(false);
    toast.info("Settings reset to defaults.");
  };

  return (
    <div className="p-4 lg:p-8 max-w-4xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold text-foreground flex items-center gap-2">
            <Settings className="h-6 w-6 text-accent" /> Settings
          </h1>
          <p className="text-muted-foreground text-sm mt-1">Customize CognitoQ for your institution.</p>
        </div>
        <div className="flex gap-2">
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="outline" size="sm" className="gap-1.5">
                <RotateCcw className="h-3.5 w-3.5" /> Reset
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Reset all settings?</AlertDialogTitle>
                <AlertDialogDescription>This will restore all settings to their default values. This action cannot be undone.</AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={resetAll}>Reset</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
          <Button size="sm" className="gap-1.5 bg-accent text-accent-foreground hover:bg-accent/90" onClick={save} disabled={!hasChanges}>
            <Save className="h-3.5 w-3.5" /> Save Changes
          </Button>
        </div>
      </motion.div>

      <Tabs defaultValue="general" className="space-y-4">
        <TabsList className="w-full flex-wrap h-auto gap-1 bg-muted/60 p-1.5 rounded-lg">
          <TabsTrigger value="general" className="gap-1.5 text-xs"><Settings className="h-3.5 w-3.5" />General</TabsTrigger>
          <TabsTrigger value="paper" className="gap-1.5 text-xs"><FileText className="h-3.5 w-3.5" />Paper</TabsTrigger>
          <TabsTrigger value="ai" className="gap-1.5 text-xs"><Brain className="h-3.5 w-3.5" />AI</TabsTrigger>
          {isAdmin && <TabsTrigger value="subjects" className="gap-1.5 text-xs"><BookOpen className="h-3.5 w-3.5" />Subjects</TabsTrigger>}
          <TabsTrigger value="branding" className="gap-1.5 text-xs"><Palette className="h-3.5 w-3.5" />Branding</TabsTrigger>
          {isAdmin && <TabsTrigger value="security" className="gap-1.5 text-xs"><Shield className="h-3.5 w-3.5" />Security</TabsTrigger>}
          <TabsTrigger value="export" className="gap-1.5 text-xs"><Download className="h-3.5 w-3.5" />Export</TabsTrigger>
        </TabsList>

        {/* ─── GENERAL ─── */}
        <TabsContent value="general" className="space-y-4">
          <SectionCard title="Institution Details" icon={Settings}>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label className="text-xs">College / Institution Name</Label>
                <Input value={settings.collegeName} onChange={e => update("collegeName", e.target.value)} placeholder="e.g. CMR College of Engineering" />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Default Exam Type</Label>
                <Select value={settings.defaultExamType} onValueChange={v => update("defaultExamType", v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="mid">Mid Semester</SelectItem>
                    <SelectItem value="end">End Semester</SelectItem>
                    <SelectItem value="internal">Internal Assessment</SelectItem>
                    <SelectItem value="supply">Supplementary</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Default Duration (minutes)</Label>
                <Input type="number" value={settings.defaultDuration} onChange={e => update("defaultDuration", e.target.value)} />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Default Max Marks</Label>
                <Input type="number" value={settings.defaultMaxMarks} onChange={e => update("defaultMaxMarks", e.target.value)} />
              </div>
            </div>
          </SectionCard>

          <SectionCard title="Paper Formatting" icon={FileText} delay={0.05}>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <Label className="text-sm">Include Instructions Section</Label>
                <Switch checked={settings.includeInstructions} onCheckedChange={v => update("includeInstructions", v)} />
              </div>
              <div className="flex items-center justify-between">
                <Label className="text-sm">Auto-number Questions</Label>
                <Switch checked={settings.autoNumberQuestions} onCheckedChange={v => update("autoNumberQuestions", v)} />
              </div>
              <div className="flex items-center justify-between">
                <Label className="text-sm">Show Marks Alignment</Label>
                <Switch checked={settings.showMarksAlignment} onCheckedChange={v => update("showMarksAlignment", v)} />
              </div>
            </div>
          </SectionCard>
        </TabsContent>

        {/* ─── PAPER ─── */}
        <TabsContent value="paper" className="space-y-4">
          <SectionCard title="Paper Generation Defaults" icon={FileText}>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label className="text-xs">Default Number of Sections</Label>
                <Select value={settings.defaultSections} onValueChange={v => update("defaultSections", v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="2">2 Sections (A, B)</SelectItem>
                    <SelectItem value="3">3 Sections (A, B, C)</SelectItem>
                    <SelectItem value="4">4 Sections (A, B, C, D)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Default Marks Pattern</Label>
                <Select value={settings.defaultMarksPattern} onValueChange={v => update("defaultMarksPattern", v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="2-5-10">2 - 5 - 10 (Standard)</SelectItem>
                    <SelectItem value="2-5-15">2 - 5 - 15 (Extended)</SelectItem>
                    <SelectItem value="1-3-5">1 - 3 - 5 (Short)</SelectItem>
                    <SelectItem value="2-10">2 - 10 (Two-tier)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Default Difficulty Level</Label>
                <Select value={settings.defaultDifficulty} onValueChange={v => update("defaultDifficulty", v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="easy">Easy</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="hard">Hard</SelectItem>
                    <SelectItem value="mixed">Mixed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="flex items-center justify-between pt-2">
              <div>
                <Label className="text-sm">OR Questions (A/B Alternatives)</Label>
                <p className="text-xs text-muted-foreground">Enable alternative questions by default</p>
              </div>
              <Switch checked={settings.orQuestionsDefault} onCheckedChange={v => update("orQuestionsDefault", v)} />
            </div>
          </SectionCard>
        </TabsContent>

        {/* ─── AI ─── */}
        <TabsContent value="ai" className="space-y-4">
          <SectionCard title="AI Generation Mode" icon={Brain}>
            <div className="space-y-3">
              {[
                { value: "strict", label: "Strict Mode", desc: "Questions generated only from uploaded notes. No external knowledge." },
                { value: "balanced", label: "Balanced Mode", desc: "Combines notes with question bank for comprehensive coverage." },
                { value: "creative", label: "Creative Mode", desc: "AI expands on topics for deeper, application-based questions." },
              ].map(mode => (
                <label key={mode.value}
                  className={`flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-colors ${settings.aiMode === mode.value ? "border-accent bg-accent/5" : "border-border hover:border-accent/40"}`}
                  onClick={() => update("aiMode", mode.value)}
                >
                  <div className={`mt-0.5 h-4 w-4 rounded-full border-2 flex items-center justify-center ${settings.aiMode === mode.value ? "border-accent" : "border-muted-foreground/40"}`}>
                    {settings.aiMode === mode.value && <div className="h-2 w-2 rounded-full bg-accent" />}
                  </div>
                  <div>
                    <span className="text-sm font-medium text-foreground">{mode.label}</span>
                    <p className="text-xs text-muted-foreground">{mode.desc}</p>
                  </div>
                </label>
              ))}
            </div>
          </SectionCard>

          <SectionCard title="Shuffle Settings" icon={Brain} delay={0.05}>
            <div className="space-y-1.5">
              <Label className="text-xs">Minimum Shuffle Variants</Label>
              <Select value={settings.shuffleLimit} onValueChange={v => update("shuffleLimit", v)}>
                <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {["4", "5", "6", "8", "10"].map(n => (
                    <SelectItem key={n} value={n}>{n} variants</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">Minimum number of unique paper variants when shuffling.</p>
            </div>
          </SectionCard>
        </TabsContent>

        {/* ─── SUBJECTS (Admin only) ─── */}
        {isAdmin && (
          <TabsContent value="subjects" className="space-y-4">
            <SectionCard title="Subject & Academic Management" icon={BookOpen}>
              <div className="flex items-center gap-2 mb-2"><AdminBadge /></div>
              <p className="text-sm text-muted-foreground">
                Manage subjects, units, and syllabus topics from the <span className="font-medium text-foreground">Subject Library</span> page. 
                Changes made there will reflect across all paper generation workflows.
              </p>
              <div className="grid sm:grid-cols-3 gap-3 pt-2">
                <div className="rounded-lg border border-border p-3 text-center">
                  <p className="text-2xl font-bold text-foreground">50+</p>
                  <p className="text-xs text-muted-foreground">Subjects Loaded</p>
                </div>
                <div className="rounded-lg border border-border p-3 text-center">
                  <p className="text-2xl font-bold text-foreground">250+</p>
                  <p className="text-xs text-muted-foreground">Units Mapped</p>
                </div>
                <div className="rounded-lg border border-border p-3 text-center">
                  <p className="text-2xl font-bold text-foreground">R22</p>
                  <p className="text-xs text-muted-foreground">Regulation</p>
                </div>
              </div>
            </SectionCard>
          </TabsContent>
        )}

        {/* ─── BRANDING ─── */}
        <TabsContent value="branding" className="space-y-4">
          <SectionCard title="College Branding" icon={Palette}>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label className="text-xs">College Logo URL</Label>
                <Input value={settings.logoUrl} onChange={e => update("logoUrl", e.target.value)} placeholder="https://..." />
                <p className="text-xs text-muted-foreground">Used in exported paper headers.</p>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Header Format</Label>
                <Select value={settings.headerFormat} onValueChange={v => update("headerFormat", v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="centered">Centered</SelectItem>
                    <SelectItem value="left-aligned">Left Aligned</SelectItem>
                    <SelectItem value="logo-left">Logo Left + Text Right</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </SectionCard>

          <SectionCard title="Paper Theme" icon={Palette} delay={0.05}>
            <div className="grid sm:grid-cols-3 gap-3">
              {[
                { value: "classic", label: "University Classic", desc: "Traditional exam paper style" },
                { value: "minimal", label: "Modern Minimal", desc: "Clean, contemporary look" },
                { value: "university", label: "JNTU Style", desc: "Standard university format" },
              ].map(theme => (
                <label key={theme.value}
                  className={`p-3 rounded-lg border text-center cursor-pointer transition-all ${settings.paperTheme === theme.value ? "border-accent bg-accent/5 ring-1 ring-accent" : "border-border hover:border-accent/40"}`}
                  onClick={() => update("paperTheme", theme.value)}
                >
                  <p className="text-sm font-medium text-foreground">{theme.label}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">{theme.desc}</p>
                </label>
              ))}
            </div>
          </SectionCard>
        </TabsContent>

        {/* ─── SECURITY (Admin only) ─── */}
        {isAdmin && (
          <TabsContent value="security" className="space-y-4">
            <SectionCard title="Session & Security" icon={Shield}>
              <div className="flex items-center gap-2 mb-2"><AdminBadge /></div>
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label className="text-xs">Session Timeout (minutes)</Label>
                  <Select value={settings.sessionTimeout} onValueChange={v => update("sessionTimeout", v)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="15">15 minutes</SelectItem>
                      <SelectItem value="30">30 minutes</SelectItem>
                      <SelectItem value="60">1 hour</SelectItem>
                      <SelectItem value="120">2 hours</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-3 pt-2">
                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-sm">Approval Notifications</Label>
                    <p className="text-xs text-muted-foreground">Get notified when new users sign up</p>
                  </div>
                  <Switch checked={settings.approvalNotifications} onCheckedChange={v => update("approvalNotifications", v)} />
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-sm">Activity Logs</Label>
                    <p className="text-xs text-muted-foreground">Track paper generation and user activity</p>
                  </div>
                  <Switch checked={settings.activityLogs} onCheckedChange={v => update("activityLogs", v)} />
                </div>
              </div>
            </SectionCard>
          </TabsContent>
        )}

        {/* ─── EXPORT ─── */}
        <TabsContent value="export" className="space-y-4">
          <SectionCard title="Export Defaults" icon={Download}>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label className="text-xs">Default Export Format</Label>
                <Select value={settings.defaultExportFormat} onValueChange={v => update("defaultExportFormat", v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="pdf">PDF</SelectItem>
                    <SelectItem value="docx">DOCX (Word)</SelectItem>
                    <SelectItem value="txt">TXT (Plain Text)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </SectionCard>

          <SectionCard title="Watermark & Footer" icon={FileText} delay={0.05}>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <Label className="text-sm">Enable Watermark</Label>
                  <p className="text-xs text-muted-foreground">Add watermark to exported papers</p>
                </div>
                <Switch checked={settings.watermarkEnabled} onCheckedChange={v => update("watermarkEnabled", v)} />
              </div>
              {settings.watermarkEnabled && (
                <div className="space-y-1.5">
                  <Label className="text-xs">Watermark Text</Label>
                  <Input value={settings.watermarkText} onChange={e => update("watermarkText", e.target.value)} />
                </div>
              )}
              <div className="space-y-1.5">
                <Label className="text-xs">Footer Text</Label>
                <Input value={settings.footerText} onChange={e => update("footerText", e.target.value)} placeholder="CognitoQ – AI Validated Paper" />
              </div>
            </div>
          </SectionCard>
        </TabsContent>
      </Tabs>
    </div>
  );
}
